### Data Combining
Using `pandas.merge()` to merge all IoT datasets by intersecting `date-time` variable. Resulting dataframe have **26525 unique entries** and **19 variables**

<br>
<br>
<br>

In [1]:
# Importing required modules

import pandas as pd

In [2]:
# read csv files of processed data for all IoT devices

IoT_Fridge = pd.read_csv("./processed_data/IoT_Fridge.csv")
IoT_Garage_Door = pd.read_csv("./processed_data/IoT_Garage_Door.csv")
IoT_GPS_Tracker = pd.read_csv("./processed_data/IoT_GPS_Tracker.csv")
IoT_Modbus = pd.read_csv("./processed_data/IoT_Modbus.csv")
IoT_Motion_Light = pd.read_csv("./processed_data/IoT_Motion_Light.csv")
IoT_Thermostat = pd.read_csv("./processed_data/IoT_Thermostat.csv")
IoT_Weather = pd.read_csv("./processed_data/IoT_Weather.csv")

In [3]:
# print shape(rows, columns) of all datasets
print(IoT_Fridge.shape, IoT_Garage_Door.shape, IoT_GPS_Tracker.shape, IoT_Modbus.shape, IoT_Motion_Light.shape, IoT_Thermostat.shape, IoT_Weather.shape)

# merge datasets, start with two and then in a cycle merge the output with another dataset
data = pd.merge(IoT_Fridge, IoT_Garage_Door, on="date-time", how="inner")
data = pd.merge(data, IoT_GPS_Tracker, on="date-time", how="inner")
data = pd.merge(data, IoT_Modbus, on="date-time", how="inner")
data = pd.merge(data, IoT_Motion_Light, on="date-time", how="inner")
data = pd.merge(data, IoT_Thermostat, on="date-time", how="inner")
data = pd.merge(data, IoT_Weather, on="date-time", how="inner")
data

(175731, 5) (161162, 5) (197431, 5) (210409, 7) (199612, 5) (197528, 5) (188312, 6)

,date-time,fridge_temperature,fridge_temp_condition,fridge_label,fridge_type,door_state,door_sphone_signal,door_label,door_type,gps_latitude,...,ml_type,thermostat_current_temperature,thermostat_status,thermostat_label,thermostat_type,weather_temperature,weather_pressure,weather_humidity,weather_label,weather_type
0,2019-03-31 12:36:52,13.10,high,0,normal,closed,False,0,normal,0.000000,...,normal,25.000000,0,0,normal,31.788508,1.035000,32.036579,0,normal
1,2019-03-31 12:36:53,8.65,high,0,normal,closed,False,0,normal,0.000000,...,normal,25.000000,0,0,normal,41.630997,1.035000,30.886165,0,normal
2,2019-03-31 12:36:54,2.00,low,0,normal,closed,False,0,normal,0.000000,...,normal,25.000000,0,0,normal,42.256959,1.035000,19.755908,0,normal
3,2019-03-31 12:36:55,4.80,low,0,normal,closed,False,0,normal,0.000000,...,normal,25.000000,0,0,normal,49.116581,1.035000,78.949621,0,normal
4,2019-03-31 12:36:56,10.70,high,0,normal,closed,False,0,normal,0.000000,...,normal,25.000000,0,0,normal,24.017085,1.035000,40.001059,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26520,2019-04-29 12:02:50,8.55,high,0,normal,closed,False,0,normal,20.284767,...,normal,26.671858,1,0,normal,42.609946,-0.859714,67.537021,0,normal
26521,2019-04-29 12:03:00,2.00,low,0,normal,closed,False,0,normal,20.389064,...,normal,26.069344,1,0,normal,43.092102,-0.859714,67.537021,0,normal
26522,2019-04-29 12:03:10,5.05,low,0,normal,closed,False,0,normal,20.418901,...,normal,25.598572,1,0,normal,42.626400,-0.859714,65.651113,0,normal
26523,2019-04-29 12:03:20,13.25,high,0,normal,closed,False,0,normal,20.427674,...,normal,28.762166,0,0,normal,42.478536,-0.859714,66.159990,0,normal
26524,2019-04-29 12:04:38,9.55,high,0,normal,closed,False,0,normal,20.123380,...,normal,29.381776,1,0,normal,45.176264,-1.518638,79.765005,0,normal

In [4]:
# infer and convert to pandas datatypes
data = data.convert_dtypes(infer_objects=True, convert_string=True,
          convert_integer=True, convert_boolean=True, convert_floating=True)
data['date-time'] = pd.to_datetime(data['date-time'])

# data = data.drop(["fridge_label", "door_label", "gps_label", "modbus_label", "ml_label", "thermostat_label", "weather_label", "fridge_type", "door_type", "gps_type", "modbus_type", "ml_type", "thermostat_type", "weather_type"], axis=1)

data = data.drop(["fridge_label", "door_label", "gps_label", "modbus_label", "ml_label", "thermostat_label", "weather_label", "fridge_type", "door_type", "gps_type", "modbus_type", "ml_type", "thermostat_type"], axis=1)
data.info()

# save final output as csv
data.to_csv("./merged_data/merged_data.csv", index=False, date_format='%d-%m-%y~%H:%M:%S')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26525 entries, 0 to 26524
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   date-time                         26525 non-null  datetime64[ns]
 1   fridge_temperature                26525 non-null  Float64
 2   fridge_temp_condition             26525 non-null  string
 3   door_state                        26525 non-null  string
 4   door_sphone_signal                26525 non-null  boolean
 5   gps_latitude                      26525 non-null  Float64
 6   gps_longitude                     26525 non-null  Float64
 7   modbus_FC1_Read_Input_Register    26525 non-null  Int64
 8   modbus_FC2_Read_Discrete_Value    26525 non-null  Int64
 9   modbus_FC3_Read_Holding_Register  26525 non-null  Int64
 10  modbus_FC4_Read_Coil              26525 non-null  Int64
 11  ml_motion_status                  26525 non-null  Int64
 12  ml_light_status                   26525 non-null  string
 13  thermostat_current_temperature    26525 non-null  Float64
 14  thermostat_status                 26525 non-null  Int64
 15  weather_temperature               26525 non-null  Float64
 16  weather_pressure                  26525 non-null  Float64
 17  weather_humidity                  26525 non-null  Float64
 18  weather_type                      26525 non-null  string
dtypes: Float64(7), Int64(6), boolean(1), datetime64[ns](1), string(4)
memory usage: 4.2 MB

<br>
<br>
<center><b>End of File</b></center>